//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaceiWeb
{
    public partial class Captura
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtMatricula;
        protected global::System.Web.UI.WebControls.TextBox txtCarrera;
        protected global::System.Web.UI.WebControls.DropDownList ddlSemestre;
        protected global::System.Web.UI.WebControls.TextBox txtComentarios;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
    }
}
