//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaceiWeb
{
    public partial class Default
    {
        protected global::System.Web.UI.WebControls.Panel pnlAdmin;
    }
}
