//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaceiWeb
{
    public partial class Listado
    {
        protected global::System.Web.UI.WebControls.Panel pnlMensaje;
        protected global::System.Web.UI.WebControls.Label lblMensaje;
        protected global::System.Web.UI.WebControls.GridView gvRegistros;
        protected global::System.Web.UI.WebControls.Button btnRefrescar;
    }
}
