//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaceiWeb
{
    public partial class SiteMaster
    {
        protected global::System.Web.UI.WebControls.Panel pnlUserBar;
        protected global::System.Web.UI.WebControls.Literal litNombreUsuario;
        protected global::System.Web.UI.WebControls.Literal litRolUsuario;
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
        protected global::System.Web.UI.WebControls.Panel pnlMenuAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlMenuPresidente;
        protected global::System.Web.UI.WebControls.Panel pnlMenuProfesor;
        protected global::System.Web.UI.WebControls.Panel pnlLoginLink;
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
