//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaceiWeb.Admin
{
    public partial class ImportarAcademias
    {
        protected global::System.Web.UI.WebControls.Panel pnlUpload;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.FileUpload fuArchivo;
        protected global::System.Web.UI.WebControls.Button btnAnalizar;
        protected global::System.Web.UI.WebControls.Panel pnlPreview;
        protected global::System.Web.UI.WebControls.Panel pnlWarnings;
        protected global::System.Web.UI.WebControls.Literal litWarnings;
        protected global::System.Web.UI.WebControls.Repeater rptPreview;
        protected global::System.Web.UI.WebControls.Literal litTotal;
        protected global::System.Web.UI.WebControls.Literal litValidos;
        protected global::System.Web.UI.WebControls.Literal litErrores;
        protected global::System.Web.UI.WebControls.Button btnImportar;
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        protected global::System.Web.UI.WebControls.Panel pnlResultado;
        protected global::System.Web.UI.WebControls.Literal litResultado;
    }
}
