//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaceiWeb.Admin
{
    public partial class UsuarioForm
    {
        protected global::System.Web.UI.WebControls.Literal litTitulo;
        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.TextBox txtNombre;
        protected global::System.Web.UI.WebControls.TextBox txtCorreo;
        protected global::System.Web.UI.WebControls.Literal litPasswordLabel;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.Panel pnlPasswordHint;
        protected global::System.Web.UI.WebControls.DropDownList ddlRol;
        protected global::System.Web.UI.WebControls.CheckBoxList chkAcademias;
        protected global::System.Web.UI.WebControls.Panel pnlEstado;
        protected global::System.Web.UI.WebControls.CheckBox chkActivo;
        protected global::System.Web.UI.WebControls.Button btnGuardar;
    }
}
